{{- if not .Values.config.clickhouse.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "radar-gateway.fullname" . }}-clickhouse
  labels:
    {{- include "radar-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.config.clickhouse.user | quote }}
  password: {{ .Values.config.clickhouse.password | quote }}
{{- end }}
