extensions:
  health_check:
    endpoint: ${env:RADAR_GATEWAY_HEALTH_ENDPOINT}

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:RADAR_GATEWAY_OTLP_GRPC_ENDPOINT}
      http:
        endpoint: ${env:RADAR_GATEWAY_OTLP_HTTP_ENDPOINT}

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 80
    spike_limit_percentage: 15
  batch:
    timeout: 2s
    send_batch_size: 1024

exporters:
  clickhouse/logs:
    endpoint: ${env:RADAR_CLICKHOUSE_ENDPOINT}
    username: ${env:RADAR_CLICKHOUSE_USER}
    password: ${env:RADAR_CLICKHOUSE_PASSWORD}
    database: ${env:RADAR_CLICKHOUSE_LOGS_DATABASE}
    create_schema: false
    logs_table_name: otel_logs
    traces_table_name: ""
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 30s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 256
      batch:
        min_size: 64
        flush_timeout: 2s

  clickhouse/traces:
    endpoint: ${env:RADAR_CLICKHOUSE_ENDPOINT}
    username: ${env:RADAR_CLICKHOUSE_USER}
    password: ${env:RADAR_CLICKHOUSE_PASSWORD}
    database: ${env:RADAR_CLICKHOUSE_TRACES_DATABASE}
    create_schema: false
    traces_table_name: otel_traces
    logs_table_name: ""
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 30s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 256
      batch:
        min_size: 64
        flush_timeout: 2s

  clickhouse/metrics:
    endpoint: ${env:RADAR_CLICKHOUSE_ENDPOINT}
    username: ${env:RADAR_CLICKHOUSE_USER}
    password: ${env:RADAR_CLICKHOUSE_PASSWORD}
    database: ${env:RADAR_CLICKHOUSE_METRICS_DATABASE}
    create_schema: false
    logs_table_name: ""
    traces_table_name: ""
    metrics_tables:
      gauge:
        name: otel_metrics_gauge
      sum:
        name: otel_metrics_sum
      summary:
        name: otel_metrics_summary
      histogram:
        name: otel_metrics_histogram
      exponential_histogram:
        name: otel_metrics_exp_histogram
    timeout: 10s
    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 30s
    sending_queue:
      enabled: true
      num_consumers: 2
      queue_size: 256
      batch:
        min_size: 64
        flush_timeout: 2s

service:
  extensions: [health_check]
  telemetry:
    logs:
      level: ${env:RADAR_LOG_LEVEL}
    metrics:
      level: none
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse/logs]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse/traces]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [clickhouse/metrics]
